### ISSUE TITLE
Mining fatigue does not disappear

### ISSUE THREAD

**Issue by M3nace** [mrbelieve-no/MoreVanillaWeapons#1]
Hello !
I've encountered a bug with the mining fatigue status while holding a shield + any two-handed weapons.

If I equip a shield + any two-handed weapons, mining fatigue status appears.
But if I unequip the shield or the two-handed weapons, the status does not disappear and stay with a timer set to 00:00.
The solution is to deconnect/reconnect.

Minecraft version : 1.20.1 with Forge
MVW version : Mvw-2.3.2b.jar

I can provide more infos if necessary.
Cheers !

**Comment by mrbelieve-no** [comment]
I'll fix it as soon as I can thanks for letting me know

**Comment by M3nace** [comment]
Hello,

I've updated the mod to mvw-2.3.3b, and the mining fatigue disappears :)
Thank you very much !

Regards,
